#!/bin/bash

# Pulse Engine - Build Script
# This script compiles the project using the build system generated by generate.sh
# It wraps CMake's build command with convenient options and error handling

set -e  # Exit on any error

# Get the script's directory (the scripts folder)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Navigate to project root (one level up from scripts)
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

# Default values
BUILD_DIR=""  # Will be auto-determined based on BUILD_TYPE if not specified
BUILD_TYPE="Release"  # Will be detected from build directory
TARGET="all"
JOBS=""  # Empty means auto-detect
VERBOSE=false
CLEAN=false
AUTO_BUILD_DIR=true  # Flag to track if we're using auto-detection

# Color codes for pretty output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored messages
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Display usage information
show_usage() {
    cat << EOF
Pulse Engine - Build Script

Usage: $0 [OPTIONS]

Options:
    -t, --type TYPE         Build type: Debug, Release, RelWithDebInfo, MinSizeRel
                           If specified, builds from build-{type} directory
                           Can't be used with --build-dir
    -b, --build-dir DIR     Build directory path
                           If not specified, uses build-release/ by default
    -t, --target TARGET     Specific target to build (default: all)
    -j, --jobs N           Number of parallel build jobs
                           If not specified, uses all available cores
    -v, --verbose          Enable verbose build output
    -c, --clean            Clean before building
    -h, --help             Show this help message

Examples:
    $0                          # Build Release from build-release/
    $0 -t Debug                 # Build Debug from build-debug/
    $0 -t Release -j 4          # Build Release using 4 parallel jobs
    $0 --target app             # Build only the 'app' target (from build-release/)
    $0 -t Debug -c -v           # Clean Debug build with verbose output
    $0 -b custom-build          # Build from custom directory

EOF
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -b|--build-dir)
            BUILD_DIR="$2"
            shift 2
            ;;
        -t|--target)
            TARGET="$2"
            shift 2
            ;;
        -j|--jobs)
            JOBS="$2"
            shift 2
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -c|--clean)
            CLEAN=true
            shift
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
done

# Auto-determine build directory if not specified by user
if [ "$AUTO_BUILD_DIR" = true ]; then
    # Convert build type to lowercase for directory name
    BUILD_TYPE_LOWER=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
    BUILD_DIR="$PROJECT_ROOT/build/build-${BUILD_TYPE_LOWER}"
    print_info "Using automatic build directory for $BUILD_TYPE configuration"
fi

# Check if build directory exists
if [ ! -d "$BUILD_DIR" ]; then
    print_error "Build directory does not exist: $BUILD_DIR"
    print_info ""
    if [ -n "$BUILD_TYPE" ]; then
        print_info "To generate this configuration, run:"
        print_info "  ./scripts/generate.sh -t $BUILD_TYPE"
    else
        print_info "Please run generate.sh first to create the build system"
        print_info "Examples:"
        print_info "  ./scripts/generate.sh -t Debug"
        print_info "  ./scripts/generate.sh -t Release"
    fi
    exit 1
fi

# Check if CMakeCache.txt exists (indicates successful configuration)
if [ ! -f "$BUILD_DIR/CMakeCache.txt" ]; then
    print_error "CMakeCache.txt not found in build directory"
    print_info "The build system may not be properly configured"
    print_info ""
    if [ -n "$BUILD_TYPE" ]; then
        print_info "To generate this configuration, run:"
        print_info "  ./scripts/generate.sh -t $BUILD_TYPE"
    else
        print_info "Please run generate.sh to configure the build"
    fi
    exit 1
fi

# Try to detect the build type from CMakeCache.txt if not already known
if [ -z "$BUILD_TYPE" ]; then
    if [ -f "$BUILD_DIR/CMakeCache.txt" ]; then
        BUILD_TYPE=$(grep "CMAKE_BUILD_TYPE:" "$BUILD_DIR/CMakeCache.txt" | cut -d'=' -f2)
        if [ -z "$BUILD_TYPE" ]; then
            BUILD_TYPE="Unknown"
        fi
    fi
fi

# Detect number of CPU cores if jobs not specified
if [ -z "$JOBS" ]; then
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        JOBS=$(nproc)
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        JOBS=$(sysctl -n hw.ncpu)
    else
        JOBS=1
        print_warning "Could not detect CPU cores, using single thread"
    fi
    print_info "Auto-detected $JOBS CPU cores for parallel building"
fi

# Print configuration
echo ""
print_info "================================================"
print_info "Pulse Engine - Build"
print_info "================================================"
print_info "Build dir:     $BUILD_DIR"
if [ -n "$BUILD_TYPE" ] && [ "$BUILD_TYPE" != "Unknown" ]; then
    print_info "Build type:    $BUILD_TYPE"
fi
print_info "Target:        $TARGET"
print_info "Parallel jobs: $JOBS"
print_info "Verbose:       $VERBOSE"
print_info "Clean build:   $CLEAN"
print_info "================================================"
echo ""

# Navigate to build directory
cd "$BUILD_DIR"

# Clean if requested
if [ "$CLEAN" = true ]; then
    print_info "Cleaning build artifacts..."
    if cmake --build . --target clean; then
        print_success "Clean completed"
    else
        print_warning "Clean failed, continuing anyway..."
    fi
    echo ""
fi

# Prepare build command
CMAKE_CMD="cmake --build ."
CMAKE_CMD="$CMAKE_CMD --target $TARGET"
CMAKE_CMD="$CMAKE_CMD --parallel $JOBS"

if [ "$VERBOSE" = true ]; then
    CMAKE_CMD="$CMAKE_CMD --verbose"
fi

# Record start time
START_TIME=$(date +%s)

# Execute build
print_info "Building target '$TARGET'..."
print_info "Command: $CMAKE_CMD"
echo ""

if eval $CMAKE_CMD; then
    # Calculate build time
    END_TIME=$(date +%s)
    BUILD_TIME=$((END_TIME - START_TIME))

    echo ""
    print_success "================================================"
    print_success "Build completed successfully!"
    print_success "================================================"
    print_info "Build time: ${BUILD_TIME} seconds"
    print_info "Output directory: $BUILD_DIR/bin"
    print_info ""

    # Try to list the built executables
    if [ -d "$BUILD_DIR/bin" ]; then
        print_info "Built executables:"
        for exe in "$BUILD_DIR/bin"/*; do
            if [ -f "$exe" ] && [ -x "$exe" ]; then
                print_info "  - $(basename "$exe")"
            fi
        done
    fi

    print_success "================================================"
    exit 0
else
    # Calculate build time even on failure
    END_TIME=$(date +%s)
    BUILD_TIME=$((END_TIME - START_TIME))

    echo ""
    print_error "================================================"
    print_error "Build failed!"
    print_error "================================================"
    print_error "Build time before failure: ${BUILD_TIME} seconds"
    print_error "Please check the error messages above"
    print_info ""
    print_info "Tips for debugging:"
    print_info "  - Run with --verbose for detailed output"
    print_info "  - Try cleaning and rebuilding: $0 --clean"
    print_info "  - Check if all dependencies are installed"
    print_info "  - Verify your CMakeLists.txt files for errors"
    print_error "================================================"
fi
